### ISSUE TITLE
Separate indicator state per window

### ISSUE THREAD

**Issue by jaller94** [lukasz-duda/ErrorIndicator#9]
Version: 1.9
Browser: Firefox Nightly 61

There seems to be one global state whereas it should be one per window.

### Steps 
1. Open a page with an error
2. Open a new browser window

### Expected
The old window keeps its status, indicating that an error occurred in the visible tab.

### Actual
The indicators in both windows become green.

**Comment by lukasz-duda** [comment]
Hi,
Thanks for your feedback!
Initial version of ErrorIndicator didn't support tab separation and it seems that when I added that feature, I didn't notice, that I should pass tab identifier argument in order to show the icon and its text in context of the tab.
I will test it for a while and publish new version soon.

Regards
Łukasz

**Comment by lukasz-duda** [comment]
I've published version 1.10, can you test it?

Changes:
* Tab identifier is passed as an argument of the request to show icon and text.
* Change of window causes update.

**Comment by jaller94** [comment]
Tested every case that I thought might break the feature.
Works perfectly well. Thanks so much! This is amazing! 🎉

**Comment by lukasz-duda** [comment]
Thanks for your help! I'm closing the issue.
